package io.angularpay.pmt.models;

public enum UserNotificationType {
    INVESTMENT_VERIFIED,
    SOLO_INVESTOR_ADDED,
    PEER_INVESTOR_ADDED,
    INVESTOR_BARGAIN_ADDED,
    BARGAIN_ACCEPTED,
    BARGAIN_REJECTED,
    INVESTOR_DELETED_BY_TTL,
    INVESTOR_DELETED_BY_SELF,
    INVESTMENT_DEACTIVATED,
    INVESTMENT_ACTIVATED,
    INVESTMENT_COMPLETED,
    INVESTMENT_CANCELLED;
}
